### ISSUE TITLE
PREP - Reference Error (Failed postProcess)

### ISSUE THREAD

**Issue by langestroop** [VisLab/EEG-Clean-Tools#10]
Dear VisLab Team,

I'm a master student at the Berlin School of Mind and Brain and I'm currently using the PREP Pipeline to preprocess the EEG dataset of my thesis. 
I'm using it as an EEGlab plugin and I'm extremely impressed by your work.
However, I'm constantly encountering the same MATLAB error:

_Warning: [MATLAB:nonExistentField]
Reference to non-existent field 'referenceOut'.
_Error in prepPipeline (line 184)
        EEG = removeTrend(EEG, EEG.referenceOut);
Error in pop_prepPipeline (line 75)
        EEG = prepPipeline(EEG, params);__

At the end of the pipeline the pdf Report coherently shows:

_Reference errors: [prepPipeline failed postProcess: Reference to non-
        existent field 'referenceOut'.
        ]_

Do you have any idea about the possible cause of this error?
I've tried to "dig" into the different subfunctions but I haven't managed to find a solution yet.

The thing that puzzle me the most is that, as far as I can judge, the pipeline seems to correctly perform robust averaging and it is even able to remove bad interpolated channels (if specified). 
But because of the aforementioned error messages, I don't know whether I can trust the completion of the process. What do you think?

Many thanks for your time and consideration. 
Best regards,

Alberto Mariola

**Comment by VisLab** [comment]
This was a bug in the post-processing --- the rest of PREP worked, but if you wanted to remove the trend after, it didn't happen.  The new version 0.55.2  now fixes.
