### ISSUE TITLE
PREP removes non-interpolated channels

### ISSUE THREAD

**Issue by eioe** [VisLab/EEG-Clean-Tools#11]
I run PREP on a 32 channel EEG data where many sets have 1-3 noisy channels. Since I want to continue with a matrix of full rank, I set 'removeInterpolatedChannels' to true. However if I do so, PREP seems to remove also channels that it does not note as interpolated in the report (and accordingly in EEG.etc.noiseDetection.reference.interpolatedChannels.all). I've seen this in multiple subjects and the only pattern I could recognize is that it seems to remove 2x the amount of channels that it tracks as interpolated (e.g. leaving me with 26 channels when 3 channels had been interpolated according to the report). Which channels are removed on top of the interpolated ones, seems sort of arbitrary to me (but most likely it isn't).  Do you have any idea what could cause this issue? Is it a bug or a user-mistake? 
If I set  'removeInterpolatedChannels' to false, it seems to work fine. The rank of the new EEG.data is then 32-nic-1 (nic = number of interpolated channels) which makes sense to me since it's now referenced to average (therefore the -1).
As a workaround, I'll keep it this way and remove the interpolated channels manually. I'm just unsure whether there's something else wrong with my usage of PREP. (Which is a great tool btw!)
These are the paramters that I used:

    EEG = pop_prepPipeline(EEG,struct('ignoreBoundaryEvents', true, ...
        'referenceChannels', [1:4, 6:26, 28:32], ...
        'evaluationChannels',[1:4, 6:26, 28:32], ...
        'rereferencedChannels', [1:32], ...
        'ransacOff', false, ...
        'ransacSampleSize', 50, ...
        'ransacChannelFraction', 0.25, ...
        'ransacCorrelationThreshold', 0.75, ...
        'ransacUnbrokenTime', 0.4, ...
        'ransacWindowSeconds', 5, ...
        'srate', 250, ...
        'robustDeviationThreshold', 5, ...
        'correlationWindowSeconds', 1, ...
        'highFrequencyNoiseThreshold', 5, ...
        'correlationThreshold', 0.3, ...
        'badTimeThreshold', 0.01, ...
        'maxReferenceIterations', 4, ...
        'referenceType', 'Robust', ...
        'reportingLevel', 'Verbose', ...
        'interpolationOrder', 'Post-reference', ....
        'meanEstimateType', 'Median', ...
        'samples', EEG.pnts, ....
        'lineNoiseChannels', [1:32], ...
        'lineFrequencies', [50  100], ...
        'Fs', 250, ...
        'p', 0.01, ....
        'fScanBandWidth', 2, ...
        'taperBandWidth', 2, ...
        'taperWindowSize', 4, ...
        'pad', 0, ...
        'taperWindowStep', 1, ...
        'fPassBand', [0  125], ...
        'tau', 100, ...
        'maximumIterations', 10, ...
        'cleanupReference', false, ...
        'keepFiltered', true, ...
        'removeInterpolatedChannels', true, ...
        'reportMode', 'normal', ...
        'publishOn', true, ...
        'sessionFilePath', strcat(path_reports, filename,'_Report.pdf'), ...
        'summaryFilePath', strcat(path_reports, filename,'_Summary.html'), ...
        'consoleFID', 1));

**Comment by VisLab** [comment]
Fixed ....   the remove interpolated channels process was called twice when prep was called from pop_prepPipeline.  Thx for reporting.
