### ISSUE TITLE
performReference.m: 'interpoledChannels' field does not exist.

### ISSUE THREAD

**Issue by wanjam** [VisLab/EEG-Clean-Tools#12]
Hi,
I just tried out performReference.m using the 'pre-reference' mode.
Matlab throws an error at line 102:
`Reference to non-existent field 'interpoledChannels'.`

I guess this is just a typo and should be changed to `interpolatedChannels`.

Best,
Wanja

**Comment by VisLab** [comment]
Fixed ---thx
