### ISSUE TITLE
Errors in report publising functions

### ISSUE THREAD

**Issue by octaveEtard** [VisLab/EEG-Clean-Tools#2]
I spotted 2 typos in the report publishing functions:
- in `getErrors.m`, line 16:
          `~isfield('noiseDetection', 'errors')`
  should be:
          `isfield(noiseDetection, 'errors')`
- in `publishPrepReport.m`, line 33:
          `if (nargin <  5)`
  should be:
          `if (nargin <  4)`

**Comment by VisLab** [comment]
Thanks for pointing out...will fix in next release.

**Comment by octaveEtard** [comment]
Also in `prepPipeline.m`, line 23, the documentation reads:

> For a full listing of the defaults for each step in the pipeline, execute:
>       `showPrepDefaults(EEG)`

However it seems this function was renamed `showPipelineDefaults`

**Comment by VisLab** [comment]
Fixed bug on line 33 above.  Reported bug on line 16 was not a bug.  Every run should have an error status field.  It's substructure fields will be empty if no errors.

**Comment by VisLab** [comment]
Also did some renaming for consistency:
getPrepDefaults
getPrepVersion
showPrepDefaults

**Comment by octaveEtard** [comment]
>  Reported bug on line 16 was not a bug. Every run should have an error status field. It's substructure fields will be empty if no errors.

My comment

> in getErrors.m, line 16:
~isfield('noiseDetection', 'errors')
should be:
isfield(noiseDetection, 'errors')

was actually to point out that `'noiseDetection'` (with apostrophes) is a string, not a structure...so the `isfield` call will fail. The apostrophes should be removed.

**Comment by VisLab** [comment]
Sorry, I was focused on the ~     the ' ' were fixed in the previous release.  Thanks for reporting.  If you know of anything else please report. I am trying to clean up all issues before next release.
