### ISSUE TITLE
Should I do the channel location first?

### ISSUE THREAD

**Issue by guishuyunye-lyw** [VisLab/EEG-Clean-Tools#20]
Dear PREP pipeline group
I have scaned your paper and read the introduction to prep, I appreciate what you have done, but I still felt confuse when I use this plugin on EEGlab.  I check all the parameter setting choice, and find none directing to montage. 

All in all,  I want to want should I do with my data, before I use the tool. should I complete channel location first? should I discard the Veog channel. I cannot find any glue about that on your website.

![image](https://user-images.githubusercontent.com/20347818/90758878-42ed8400-e312-11ea-9911-ff04ed1c4c88.png)

After the process, I cannot see any change through this EEGlab interface. no channel location, no reference.

**Comment by VisLab** [comment]
This is the EEGLAB menu, not the PREP pipeline menu. It looks like you have already loaded a dataset.  Go to the Tools menu and select the menu item for the PREP pipeline.   There will be a menu with buttons for each stage.  You will need to set channel numbers in each stage.  If you don't PREP uses them all.  For line noise removal, you want to include EOG channels.  For detrend channels, you probably want to include EOG. For doing the reference, there are actually three sets of channel numbers you need to set.

1)  evaluation channels --- used to evaluate which channels are noisy (use just EEG channels)
2)  reference channels --- used to evaluate the robust average reference (use just EEG channels)
3)  rereference channels --- these channels have the robust average reference subtracted from them  (often both EEG and EOG channels are referenced, but not always --- depends on your application).

**Comment by guishuyunye-lyw** [comment]
Thank you so much for your reply! I process my data with PREP again following your advices, step by step.
Veog channel's number is the 20. I still not clear with should I do the channel location firstly.
![image](https://user-images.githubusercontent.com/20347818/90852949-6adcf600-e3ab-11ea-8aa1-e800da53763b.png)
After the channel location process through eeglab edit. I ran Prep.
![image](https://user-images.githubusercontent.com/20347818/90853013-9b249480-e3ab-11ea-9fc1-a3d2d868d1a4.png)
![image](https://user-images.githubusercontent.com/20347818/90853101-c4ddbb80-e3ab-11ea-8751-6b3870b37aee.png)
![image](https://user-images.githubusercontent.com/20347818/90853108-c909d900-e3ab-11ea-92b6-3b5f8a12457f.png)
In China, the line frequency is 50hz
![image](https://user-images.githubusercontent.com/20347818/90853117-cd35f680-e3ab-11ea-8a59-41a37759ab92.png)
Excluded 20th channel under reference channnels and evaluation channels condition.
![image](https://user-images.githubusercontent.com/20347818/90853180-f2c30000-e3ab-11ea-8d67-79db2158b92c.png)
After the whole process, I went back to eeglab interface, which shows the data is still unrereference. 
![image](https://user-images.githubusercontent.com/20347818/90853324-68c76700-e3ac-11ea-8dea-38ef41b3a5e2.png)


According to the introduction of PREP, I thought this process have completed the procedures for me:
1 high pass 
2 line noise
3 rereference 
So I just need to do a low pass process before ICA, without another rereference and other preprocesses?


I am still a amateur in processing EEG data, thx for your patience!
