### ISSUE TITLE
Crash on movefile in publishPrepReport

### ISSUE THREAD

**Issue by GregPerlman** [VisLab/EEG-Clean-Tools#23]
Prepline 0.55 crashes during publishPrepReport, whether I specify additional parameters or not (e.g., use all defaults).

One example of parameters that leads to a crash: 
'summaryFilePath', strcat('C:\Users\data\', filename, '_PREP.html') ,... 
'sessionFilePath', strcat('C:\Users\data\', filename, '_PREP.pdf') ,... 
'consoleID', 1,...
'publishOn', true);

In any test runs, Matlab credits line 73 of publishPrepReport: "movefile(tempReportLocation, sessionReportLocation);" for the error. 

The code will run to completion if I comment out that line or if I set relativeReportLocation (line 48) equal to sessionFilePath. However, only the .html file will be properly named. The .PDF will only be named "prepReport" and is overwritten if more than 1 subject is processed in a loop.

**Comment by VisLab** [comment]
'summaryFilePath', strcat('C:\Users\data', filename, '_PREP.html') 

Isn't this trying to write to C:\Users with file name dataxxx_PREP.html.  You can't directly write to Users usually.

**Comment by GregPerlman** [comment]
I was working from my Home PC (no admin issues when writing to Users.). I also tried other paths, but it gave same error. It gave same error when i provided no paths.

**Comment by VisLab** [comment]
My point was that your summaryFilePath was missing a file separator character.  You can't write to C:\Users directly without specifically running as administrator in the usual setup even if it is your home PC.   Make sure that you have a correct path by putting an explicit path in the call and creating a file outside of PREP to make sure that the exact file name you are writing to can be written to.

**Comment by VisLab** [comment]
You have to provide a path for the reports.  There is no default for this. Thanks
