### ISSUE TITLE
Interpolation prior to ICA

### ISSUE THREAD

**Issue by UHSVH** [VisLab/EEG-Clean-Tools#25]
Dear PREP pipeline team

I have a question regarding the interpolation that happens based on robust average referencing. 

Many researchers hold the view that interpolation of channels should not happen prior to ICA. What is your opinion about not interpolating prior to running ICA analysis? Does it differ from the rather conventional view as you implement interpolation prior to ICA, and if so, why? 

Hence, it seems like I should remove interpolation in the post-process menu of PREP, would you agree?

Thank you in advance!

**Comment by VisLab** [comment]
Prep gives you the options to do it either way.  The relevant options are:

in the Reference stage: the 'interpolationOrder' parameter controls when and if interpolation is performed. (The default is Post-reference, but you would want None. Pre-reference is not recommended. It is there for benchmarking purposes.). The options are:
    
            post-reference: bad channels are detected again and interpolated after referencing
            pre-reference: bad channels detected before referencing and interpolated
            none: no interpolation is performed

In the Post process section, there is also an option:   removeInterpolatedChannels which if true If true, removes channels interpolated by Prep.

As far as whether you should or not, I don't have a definitive answer on that.  I have done it both ways depending on what I am doing. This is something that deserves more benchmarking.  If you use the interpolated channels, you have to use PCA to reduce the dimension on the interpolated data.  My sense is that this does a better job of capturing spatial variability more consistently especially when you are comparing across a lot of datasets.  

On a side note, if using ASR for artifact removal, you absolutely cannot interpolate channels or the method blows up. ASR does seem to do slightly better if you remove bad channels as detected by PREP and then apply ASR.  Again, this would need more systematic benchmarking to cast as a "rule".

**Comment by balandongiv** [comment]
@VisLab , is the  `none: no interpolation is performed` still available in latest version. I notice this option is not available for version`0.55.4`. There are option for `post-reference` and `pre-reference`

![Snap 2021-07-21 at 08 19 27](https://user-images.githubusercontent.com/22090092/126411092-ba7c7a81-e200-40db-b362-c57667dc4c82.png)
