### ISSUE TITLE
Issues with Infinite Recursion

### ISSUE THREAD

**Issue by deskool** [VisLab/EEG-Clean-Tools#5]
Hello, 

I'm attempting the run the prep pipeline for a set of 72Hr long continuous EEG recordings I have collected. 

After running Prep on my EEG file, I get the following error:

"prepPipeline failed performReference: Error using catdirs (line 28) Out of memory. The likely cause is an infinite recursion within the program."

Any idea why this might be the case? Has anyone else had this error?

**Comment by VisLab** [comment]
Hello,
What is the size of your data file (in GB)?   What is the size of the
memory on your machine (in GB)?

Regards,
Kay Robbins

**Comment by deskool** [comment]
Hello Kay,

Thanks so much for getting back to me. The size of the Data-file is only 2 GB and the I have 50 GB of RAM so I'm pretty sure it's not a memory issue.

**Comment by VisLab** [comment]
Is this 2 GB before or after it has been converted to double?

On Tue, Jul 12, 2016 at 9:36 AM, Mohammad Ghassemi <notifications@github.com

**Comment by deskool** [comment]
It's 2GB after having been converted to a double - but again, I have lots of RAM.

**Comment by VisLab** [comment]
Sorry, but this is on the borderline of enough memory.  The reason is that has to keep multiple copies in order to avoid permanently high pass filtering. We may provide an option for avoiding this in the future.
Kay
